version: '3.5'

networks:
  wgerdur_network:
    name: wgerdur_network
    driver: bridge

volumes:
  wp:
    driver: local
    name: wordpress
    driver_opts:
      type: none
      o: bind
      device: /home/ewgerdur/data/wp
  db:
    driver: local
    name: db
    driver_opts:
      type: none
      o: bind
      device: /home/ewgerdur/data/db

services:
  mariadb:
    image: mariadb
    env_file: .env
    volumes:
     - db:/var/lib/mysql
    restart: always
    build: req/db/
    user: root
    networks:
      - wgerdur_network
    container_name: mariadb

  wordpress:
    depends_on:
      - mariadb
    image: wordpress
    env_file: .env
    volumes:
     - wp:/var/www/html
    restart: always
    build: req/wp/
    user: root
    networks:
      - wgerdur_network
    container_name: wordpress

  nginx:
    depends_on:
      - wordpress
    image: nginx
    volumes:
      - wp:/var/www/html
    env_file: .env
    restart: always
    build: req/nginx/
    user: root
    networks:
      - wgerdur_network
    container_name: nginx
    ports:
      - "443:443"
